// lib/city-redirects.ts — 301/308 map for city slugs retired by the 2026-07-11
// empire city-string sweep (stripAdminPrefix + Census-arbitrated abbrev merge).
// Keyed "region/old-slug" -> "region/canonical-slug" (lowercase, no leading slash;
// region = province_state lowercased). 172 entries. MACHINE-GENERATED.
//
// Resolved in app/[region]/[city]/page.tsx via permanentRedirect (308, SEO-equivalent
// to 301) — gated on the page having ZERO listings, so it is INERT until the Phase-2
// DB write empties the old slug, then activates automatically. Stamper-v3 repos ban
// middleware.ts (owner-auth cookie handling), so this is page-level by design.

export const CITY_REDIRECTS: Readonly<Record<string, string>> = {
  "al/ft-payne": "al/fort-payne",
  "al/ft-rucker": "al/fort-rucker",
  "ar/ft-smith": "ar/fort-smith",
  "ar/saint-joe": "ar/st-joe",
  "az/ft-defiance": "az/fort-defiance",
  "az/saint-johns": "az/st-johns",
  "ca/ft-bidwell": "ca/fort-bidwell",
  "ca/ft-irwin": "ca/fort-irwin",
  "ca/mt-shasta": "ca/mount-shasta",
  "ca/saint-helena": "ca/st-helena",
  "co/ft-carson": "co/fort-carson",
  "co/ft-collins": "co/fort-collins",
  "fl/ft-lauderdale": "fl/fort-lauderdale",
  "fl/ft-myers": "fl/fort-myers",
  "fl/ft-pierce": "fl/fort-pierce",
  "fl/ft-walton-beach": "fl/fort-walton-beach",
  "fl/mt-dora": "fl/mount-dora",
  "fl/port-saint-joe": "fl/port-st-joe",
  "fl/port-saint-john": "fl/port-st-john",
  "fl/port-saint-lucie": "fl/port-st-lucie",
  "fl/saint-augustine": "fl/st-augustine",
  "fl/saint-cloud": "fl/st-cloud",
  "fl/saint-james-city": "fl/st-james-city",
  "fl/saint-petersburg": "fl/st-petersburg",
  "fl/village-of-golf": "fl/golf",
  "fl/village-of-palmetto-bay": "fl/palmetto-bay",
  "ga/ft-benning": "ga/fort-benning",
  "ga/ft-gordon": "ga/fort-gordon",
  "ga/ft-oglethorpe": "ga/fort-oglethorpe",
  "ga/ft-stewart": "ga/fort-stewart",
  "ga/saint-marys": "ga/st-marys",
  "ia/ft-madison": "ia/fort-madison",
  "ia/mt-pleasant": "ia/mount-pleasant",
  "ia/saint-ansgar": "ia/st-ansgar",
  "ia/saint-charles": "ia/st-charles",
  "id/saint-anthony": "id/st-anthony",
  "id/saint-maries": "id/st-maries",
  "il/east-saint-louis": "il/east-st-louis",
  "il/mt-carmel": "il/mount-carmel",
  "il/mt-prospect": "il/mount-prospect",
  "il/mt-sterling": "il/mount-sterling",
  "il/mt-vernon": "il/mount-vernon",
  "il/mt-zion": "il/mount-zion",
  "il/saint-anne": "il/st-anne",
  "il/saint-charles": "il/st-charles",
  "il/saint-peter": "il/st-peter",
  "il/village-of-lakewood": "il/lakewood",
  "in/ft-wayne": "in/fort-wayne",
  "in/mt-vernon": "in/mount-vernon",
  "in/saint-john": "in/st-john",
  "ks/ft-riley": "ks/fort-riley",
  "ks/saint-francis": "ks/st-francis",
  "ks/saint-marys": "ks/st-marys",
  "ky/ft-campbell": "ky/fort-campbell",
  "ky/ft-mitchell": "ky/fort-mitchell",
  "ky/ft-thomas": "ky/fort-thomas",
  "ky/ft-wright": "ky/fort-wright",
  "ky/mt-sterling": "ky/mount-sterling",
  "ky/mt-washington": "ky/mount-washington",
  "la/saint-francisville": "la/st-francisville",
  "la/saint-gabriel": "la/st-gabriel",
  "la/saint-martinville": "la/st-martinville",
  "la/saint-rose": "la/st-rose",
  "md/ft-meade": "md/fort-meade",
  "md/ft-washington": "md/fort-washington",
  "md/mt-airy": "md/mount-airy",
  "mi/mt-clemens": "mi/mount-clemens",
  "mi/mt-pleasant": "mi/mount-pleasant",
  "mi/saint-charles": "mi/st-charles",
  "mi/saint-clair": "mi/st-clair",
  "mi/saint-clair-shores": "mi/st-clair-shores",
  "mi/saint-ignace": "mi/st-ignace",
  "mi/saint-johns": "mi/st-johns",
  "mi/saint-joseph": "mi/st-joseph",
  "mi/saint-louis": "mi/st-louis",
  "mi/sault-sainte-marie": "mi/sault-ste-marie",
  "mn/north-saint-paul": "mn/north-st-paul",
  "mn/saint-anthony": "mn/st-anthony",
  "mn/saint-charles": "mn/st-charles",
  "mn/saint-cloud": "mn/st-cloud",
  "mn/saint-james": "mn/st-james",
  "mn/saint-joseph": "mn/st-joseph",
  "mn/saint-louis-park": "mn/st-louis-park",
  "mn/saint-michael": "mn/st-michael",
  "mn/saint-paul": "mn/st-paul",
  "mn/saint-peter": "mn/st-peter",
  "mn/south-saint-paul": "mn/south-st-paul",
  "mn/west-saint-paul": "mn/west-st-paul",
  "mo/ft-leonard-wood": "mo/fort-leonard-wood",
  "mo/lake-saint-louis": "mo/lake-st-louis",
  "mo/saint-ann": "mo/st-ann",
  "mo/saint-charles": "mo/st-charles",
  "mo/saint-clair": "mo/st-clair",
  "mo/saint-james": "mo/st-james",
  "mo/saint-joseph": "mo/st-joseph",
  "mo/saint-louis": "mo/st-louis",
  "mo/saint-peters": "mo/st-peters",
  "mo/saint-robert": "mo/st-robert",
  "mo/sainte-genevieve": "mo/ste-genevieve",
  "ms/bay-saint-louis": "ms/bay-st-louis",
  "nc/mt-airy": "nc/mount-airy",
  "nc/mt-holly": "nc/mount-holly",
  "nc/mt-olive": "nc/mount-olive",
  "nc/mt-pleasant": "nc/mount-pleasant",
  "nc/saint-james": "nc/st-james",
  "nc/saint-pauls": "nc/st-pauls",
  "nd/ft-totten": "nd/fort-totten",
  "nd/ft-yates": "nd/fort-yates",
  "ne/saint-edward": "ne/st-edward",
  "ne/saint-paul": "ne/st-paul",
  "nj/mt-holly": "nj/mount-holly",
  "nj/mt-laurel": "nj/mount-laurel",
  "nj/township-of-long-beach": "nj/long-beach",
  "nj/township-of-washington": "nj/washington",
  "ny/mt-kisco": "ny/mount-kisco",
  "ny/mt-sinai": "ny/mount-sinai",
  "ny/mt-vernon": "ny/mount-vernon",
  "ny/saint-james": "ny/st-james",
  "oh/ft-recovery": "oh/fort-recovery",
  "oh/mt-eaton": "oh/mount-eaton",
  "oh/mt-orab": "oh/mount-orab",
  "oh/mt-vernon": "oh/mount-vernon",
  "oh/saint-clairsville": "oh/st-clairsville",
  "oh/saint-henry": "oh/st-henry",
  "oh/saint-marys": "oh/st-marys",
  "ok/ft-gibson": "ok/fort-gibson",
  "ok/ft-sill": "ok/fort-sill",
  "or/saint-helens": "or/st-helens",
  "or/saint-paul": "or/st-paul",
  "pa/ft-washington": "pa/fort-washington",
  "pa/mt-carmel": "pa/mount-carmel",
  "pa/mt-gretna": "pa/mount-gretna",
  "pa/mt-holly-springs": "pa/mount-holly-springs",
  "pa/mt-jewett": "pa/mount-jewett",
  "pa/mt-lebanon": "pa/mount-lebanon",
  "pa/mt-morris": "pa/mount-morris",
  "pa/mt-pleasant": "pa/mount-pleasant",
  "pa/mt-pleasant-mills": "pa/mount-pleasant-mills",
  "pa/mt-pocono": "pa/mount-pocono",
  "pa/saint-marys": "pa/st-marys",
  "pa/saint-thomas": "pa/st-thomas",
  "sc/mt-pleasant": "sc/mount-pleasant",
  "sc/saint-helena-island": "sc/st-helena-island",
  "sc/saint-matthews": "sc/st-matthews",
  "sc/saint-stephen": "sc/st-stephen",
  "sd/ft-thompson": "sd/fort-thompson",
  "tn/mt-juliet": "tn/mount-juliet",
  "tn/mt-pleasant": "tn/mount-pleasant",
  "tx/ft-bliss": "tx/fort-bliss",
  "tx/ft-hood": "tx/fort-hood",
  "tx/ft-stockton": "tx/fort-stockton",
  "tx/ft-worth": "tx/fort-worth",
  "tx/mt-pleasant": "tx/mount-pleasant",
  "tx/mt-vernon": "tx/mount-vernon",
  "tx/saint-hedwig": "tx/st-hedwig",
  "ut/ft-duchesne": "ut/fort-duchesne",
  "ut/mt-pleasant": "ut/mount-pleasant",
  "ut/saint-george": "ut/st-george",
  "va/ft-belvoir": "va/fort-belvoir",
  "va/ft-lee": "va/fort-lee",
  "va/saint-paul": "va/st-paul",
  "va/saint-stephens-church": "va/st-stephens-church",
  "vt/saint-albans": "vt/st-albans",
  "vt/saint-johnsbury": "vt/st-johnsbury",
  "wa/ft-lewis": "wa/fort-lewis",
  "wa/mt-vernon": "wa/mount-vernon",
  "wi/mt-horeb": "wi/mount-horeb",
  "wi/mt-pleasant": "wi/mount-pleasant",
  "wi/saint-croix-falls": "wi/st-croix-falls",
  "wi/saint-francis": "wi/st-francis",
  "wv/saint-albans": "wv/st-albans",
  "wv/saint-marys": "wv/st-marys",
};

/** Retired /{region}/{city} -> canonical pathname, or null. Bare 2-segment only. */
export function resolveCityRedirect(pathname: string): string | null {
  const parts = pathname.replace(/^\/+|\/+$/g, "").split("/");
  if (parts.length !== 2) return null;
  const key = `${parts[0].toLowerCase()}/${parts[1].toLowerCase()}`;
  const to = CITY_REDIRECTS[key];
  return to ? `/${to}` : null;
}
