const verticalConfig = {
  inquiryNoEmailPolicy: "hide", // TDL #455 (empire default)
  // === BRANDING ===
  name: "DoINeedATherapist.org",
  shortName: "DoINeedATherapist",
  tagline: "Find a trusted therapist near you",
  description: "A trusted therapist directory. AI-powered mental health triage, verified therapist listings, and a safe space to start your journey.",
  entity: "Therapist",
  entityPlural: "Therapists",
  slug: "doineedatherapist",
  domain: "www.doineedatherapist.org",
  displayDomain: "doineedatherapist.org",
  supportEmail: "hello@doineedatherapist.org",
  primaryColor: "#6B8F71",
  ctaColor: "#E17055",
  instagramHandle: "",

  // === ENTITY NOUNS ===
  listingNoun: "therapist",
  listingNounPlural: "therapists",

  // === COLORS ===
  heroGradientFrom: "#6B8F71",
  heroGradientVia: "#5A7D60",
  heroGradientTo: "#4A6B50",
  creamBg: "#FFF8F0",
  defaultCountry: "CA",

  // === COUNTRY SUPPORT (TDL #271) ===
  supportedCountries: ["CA", "US"] as const,

  // === DATABASE ===
  tablePrefix: "ther_",

  // === BILLING ===
  siteforgeEnabled: true,

  // === TRIAGE (3-question quiz instead of AI chat) ===
  triageEnabled: true,
  triageType: "quiz",
  triageQuestions: [
    {
      id: "q1",
      question: "How have you been feeling emotionally in the last 2 weeks?",
      options: [
        { label: "Good — mostly fine", score: 1 },
        { label: "Up and down — some tough days", score: 2 },
        { label: "Struggling — more bad days than good", score: 3 },
        { label: "In crisis — I need help now", score: 4, crisis: true },
      ],
    },
    {
      id: "q2",
      question: "Is stress affecting your sleep, appetite, or daily routine?",
      options: [
        { label: "Not really", score: 1 },
        { label: "Sometimes", score: 2 },
        { label: "Most days", score: 3 },
        { label: "Every day", score: 4 },
      ],
    },
    {
      id: "q3",
      question: "What kind of support interests you most?",
      options: [
        { label: "Just someone to talk to", score: 0, type: "psychotherapist" },
        { label: "Help with anxiety or stress", score: 0, type: "psychotherapist" },
        { label: "Help with depression or grief", score: 0, type: "psychologist" },
        { label: "Couples or family counselling", score: 0, type: "counsellor" },
        { label: "I'm not sure yet", score: 0, type: "psychotherapist" },
      ],
    },
  ],
  triageResults: {
    low: {
      heading: "It sounds like you're doing okay",
      body: "Checking in with yourself is always a healthy thing to do. If things change or you just want someone to talk to, therapists are here for you — no crisis required.",
      ctaStyle: "secondary",
    },
    moderate: {
      heading: "Talking to someone could really help",
      body: "Based on what you shared, connecting with a professional could make a real difference. Therapy isn't just for crisis — it's for anyone who wants support navigating life.",
      ctaStyle: "primary",
    },
    high: {
      heading: "You deserve support right now",
      body: "It sounds like you're going through a really tough time, and that takes courage to acknowledge. You don't have to go through this alone.",
      ctaStyle: "primary",
    },
  },
  crisisResources: {
    enabled: true,
    resources: [
      { label: "If you're in immediate danger, call 911", type: "emergency" },
      { label: "Talk to someone now: call or text 988", type: "crisis", url: "tel:988" },
      { label: "Crisis Text Line: text HOME to 686868", type: "crisis" },
    ],
  },
  triageDisclaimer: "This is not a clinical assessment or diagnosis. It's a tool to help you think about whether professional support might be helpful. If you are in crisis, call or text 988.",

  // === CATEGORIES ===
  categoryLabels: [
    { slug: "psychotherapist", label: "Psychotherapist", emoji: "🧠", description: "Talk therapy for anxiety, depression, trauma, and personal growth" },
    { slug: "psychologist", label: "Psychologist", emoji: "🔬", description: "Clinical assessment, diagnosis, and evidence-based treatment" },
    { slug: "counsellor", label: "Counsellor", emoji: "💬", description: "Guidance for relationships, career, grief, and life transitions" },
    { slug: "social-worker", label: "Social Worker", emoji: "🤝", description: "Mental health support with a focus on community and social systems" },
    { slug: "couples-therapist", label: "Couples Therapist", emoji: "💑", description: "Relationship counselling, communication, and conflict resolution" },
    { slug: "family-therapist", label: "Family Therapist", emoji: "👨‍👩‍👧‍👦", description: "Family dynamics, parenting challenges, and family conflict" },
    { slug: "child-therapist", label: "Child & Youth Therapist", emoji: "🧒", description: "Specialized therapy for children and adolescents" },
    { slug: "addiction-counsellor", label: "Addiction Counsellor", emoji: "🔄", description: "Support for substance use, behavioral addictions, and recovery" },
    { slug: "trauma-therapist", label: "Trauma Therapist", emoji: "🕊️", description: "PTSD, EMDR, and healing from traumatic experiences" },
    { slug: "art-therapist", label: "Art & Creative Therapist", emoji: "🎨", description: "Expressive arts therapy using art, music, or drama" },
  ],

  // === NATIONAL REGIONS ===
  regions: [
    // Ontario
    { slug: "toronto", label: "Toronto", province: "ON" },
    { slug: "ottawa", label: "Ottawa", province: "ON" },
    { slug: "mississauga", label: "Mississauga", province: "ON" },
    { slug: "brampton", label: "Brampton", province: "ON" },
    { slug: "hamilton", label: "Hamilton", province: "ON" },
    { slug: "london-on", label: "London", province: "ON" },
    { slug: "markham", label: "Markham", province: "ON" },
    { slug: "vaughan", label: "Vaughan", province: "ON" },
    { slug: "kitchener", label: "Kitchener", province: "ON" },
    { slug: "windsor", label: "Windsor", province: "ON" },
    { slug: "richmond-hill", label: "Richmond Hill", province: "ON" },
    { slug: "oakville", label: "Oakville", province: "ON" },
    { slug: "burlington", label: "Burlington", province: "ON" },
    { slug: "barrie", label: "Barrie", province: "ON" },
    { slug: "oshawa", label: "Oshawa", province: "ON" },
    { slug: "st-catharines", label: "St. Catharines", province: "ON" },
    { slug: "guelph", label: "Guelph", province: "ON" },
    { slug: "cambridge", label: "Cambridge", province: "ON" },
    { slug: "waterloo", label: "Waterloo", province: "ON" },
    { slug: "kingston", label: "Kingston", province: "ON" },
    { slug: "thunder-bay", label: "Thunder Bay", province: "ON" },
    { slug: "sudbury", label: "Sudbury", province: "ON" },
    { slug: "peterborough", label: "Peterborough", province: "ON" },
    { slug: "niagara-falls", label: "Niagara Falls", province: "ON" },
    // British Columbia
    { slug: "vancouver", label: "Vancouver", province: "BC" },
    { slug: "surrey", label: "Surrey", province: "BC" },
    { slug: "burnaby", label: "Burnaby", province: "BC" },
    { slug: "richmond-bc", label: "Richmond", province: "BC" },
    { slug: "kelowna", label: "Kelowna", province: "BC" },
    { slug: "victoria", label: "Victoria", province: "BC" },
    { slug: "nanaimo", label: "Nanaimo", province: "BC" },
    { slug: "kamloops", label: "Kamloops", province: "BC" },
    { slug: "abbotsford", label: "Abbotsford", province: "BC" },
    { slug: "coquitlam", label: "Coquitlam", province: "BC" },
    // Alberta
    { slug: "calgary", label: "Calgary", province: "AB" },
    { slug: "edmonton", label: "Edmonton", province: "AB" },
    { slug: "red-deer", label: "Red Deer", province: "AB" },
    { slug: "lethbridge", label: "Lethbridge", province: "AB" },
    { slug: "st-albert", label: "St. Albert", province: "AB" },
    { slug: "medicine-hat", label: "Medicine Hat", province: "AB" },
    { slug: "grande-prairie", label: "Grande Prairie", province: "AB" },
    // Quebec
    { slug: "montreal", label: "Montreal", province: "QC" },
    { slug: "quebec-city", label: "Quebec City", province: "QC" },
    { slug: "laval", label: "Laval", province: "QC" },
    { slug: "gatineau", label: "Gatineau", province: "QC" },
    { slug: "longueuil", label: "Longueuil", province: "QC" },
    { slug: "sherbrooke", label: "Sherbrooke", province: "QC" },
    { slug: "trois-rivieres", label: "Trois-Rivières", province: "QC" },
    // Manitoba
    { slug: "winnipeg", label: "Winnipeg", province: "MB" },
    { slug: "brandon", label: "Brandon", province: "MB" },
    // Saskatchewan
    { slug: "saskatoon", label: "Saskatoon", province: "SK" },
    { slug: "regina", label: "Regina", province: "SK" },
    // Nova Scotia
    { slug: "halifax", label: "Halifax", province: "NS" },
    { slug: "dartmouth", label: "Dartmouth", province: "NS" },
    { slug: "sydney-ns", label: "Sydney", province: "NS" },
    // New Brunswick
    { slug: "saint-john", label: "Saint John", province: "NB" },
    { slug: "moncton", label: "Moncton", province: "NB" },
    { slug: "fredericton", label: "Fredericton", province: "NB" },
    // Newfoundland
    { slug: "st-johns", label: "St. John's", province: "NL" },
    // PEI
    { slug: "charlottetown", label: "Charlottetown", province: "PE" },
    { slug: "ab", label: "Alberta", province: "AB" },
    { slug: "bc", label: "British Columbia", province: "BC" },
    { slug: "mb", label: "Manitoba", province: "MB" },
    { slug: "nb", label: "New Brunswick", province: "NB" },
    { slug: "nl", label: "Newfoundland and Labrador", province: "NL" },
    { slug: "ns", label: "Nova Scotia", province: "NS" },
    { slug: "nt", label: "Northwest Territories", province: "NT" },
    { slug: "nu", label: "Nunavut", province: "NU" },
    { slug: "on", label: "Ontario", province: "ON" },
    { slug: "pe", label: "Prince Edward Island", province: "PE" },
    { slug: "qc", label: "Quebec", province: "QC" },
    { slug: "sk", label: "Saskatchewan", province: "SK" },
    { slug: "yt", label: "Yukon", province: "YT" },
    { slug: "al", label: "Alabama", province: "AL" },
    { slug: "ak", label: "Alaska", province: "AK" },
    { slug: "az", label: "Arizona", province: "AZ" },
    { slug: "ar", label: "Arkansas", province: "AR" },
    { slug: "ca", label: "California", province: "CA" },
    { slug: "co", label: "Colorado", province: "CO" },
    { slug: "ct", label: "Connecticut", province: "CT" },
    { slug: "de", label: "Delaware", province: "DE" },
    { slug: "fl", label: "Florida", province: "FL" },
    { slug: "ga", label: "Georgia", province: "GA" },
    { slug: "hi", label: "Hawaii", province: "HI" },
    { slug: "id", label: "Idaho", province: "ID" },
    { slug: "il", label: "Illinois", province: "IL" },
    { slug: "in", label: "Indiana", province: "IN" },
    { slug: "ia", label: "Iowa", province: "IA" },
    { slug: "ks", label: "Kansas", province: "KS" },
    { slug: "ky", label: "Kentucky", province: "KY" },
    { slug: "la", label: "Louisiana", province: "LA" },
    { slug: "me", label: "Maine", province: "ME" },
    { slug: "md", label: "Maryland", province: "MD" },
    { slug: "ma", label: "Massachusetts", province: "MA" },
    { slug: "mi", label: "Michigan", province: "MI" },
    { slug: "mn", label: "Minnesota", province: "MN" },
    { slug: "ms", label: "Mississippi", province: "MS" },
    { slug: "mo", label: "Missouri", province: "MO" },
    { slug: "mt", label: "Montana", province: "MT" },
    { slug: "ne", label: "Nebraska", province: "NE" },
    { slug: "nv", label: "Nevada", province: "NV" },
    { slug: "nh", label: "New Hampshire", province: "NH" },
    { slug: "nj", label: "New Jersey", province: "NJ" },
    { slug: "nm", label: "New Mexico", province: "NM" },
    { slug: "ny", label: "New York", province: "NY" },
    { slug: "nc", label: "North Carolina", province: "NC" },
    { slug: "nd", label: "North Dakota", province: "ND" },
    { slug: "oh", label: "Ohio", province: "OH" },
    { slug: "ok", label: "Oklahoma", province: "OK" },
    { slug: "or", label: "Oregon", province: "OR" },
    { slug: "pa", label: "Pennsylvania", province: "PA" },
    { slug: "ri", label: "Rhode Island", province: "RI" },
    { slug: "sc", label: "South Carolina", province: "SC" },
    { slug: "sd", label: "South Dakota", province: "SD" },
    { slug: "tn", label: "Tennessee", province: "TN" },
    { slug: "tx", label: "Texas", province: "TX" },
    { slug: "ut", label: "Utah", province: "UT" },
    { slug: "vt", label: "Vermont", province: "VT" },
    { slug: "va", label: "Virginia", province: "VA" },
    { slug: "wa", label: "Washington", province: "WA" },
    { slug: "wv", label: "West Virginia", province: "WV" },
    { slug: "wi", label: "Wisconsin", province: "WI" },
    { slug: "wy", label: "Wyoming", province: "WY" },
    { slug: "dc", label: "District of Columbia", province: "DC" },
  ],

  // === PROVINCE LABELS ===
  provinceLabels: {
    ON: "Ontario",
    BC: "British Columbia",
    AB: "Alberta",
    QC: "Quebec",
    MB: "Manitoba",
    SK: "Saskatchewan",
    NS: "Nova Scotia",
    NB: "New Brunswick",
    NL: "Newfoundland & Labrador",
    PE: "Prince Edward Island",
  } as Record<string, string>,

  // === CROSS-REFERRAL (v7) ===
  cluster: "B",
  crossReferrals: [
    { name: 'Not Sure Which Pro?', url: 'https://doineedapro.com', description: 'Free AI triage — tell us your problem, we\'ll tell you which type of pro to call' },
    { name: "Find a Physiotherapist", url: "https://doineedaphysiotherapist.com", pathPattern: "/{city}" },
    { name: "Find a Massage Therapist", url: "https://doineedamassagetherapist.com", pathPattern: "/{city}" },
    { name: "Find a Naturopath", url: "https://doineedanaturopath.com", pathPattern: "/{city}" },
  ],

  // === FAQs ===
  faqs: [
    {
      question: "How do I know if I need a therapist?",
      answer: "If stress, anxiety, sadness, or relationship difficulties are affecting your daily life, talking to a therapist can help. You don't need to be in crisis — therapy is for anyone who wants support navigating life's challenges."
    },
    {
      question: "What's the difference between a psychologist, psychotherapist, and counsellor?",
      answer: "Psychologists have doctoral-level training and can do clinical assessments. Psychotherapists (Registered Psychotherapists in Ontario) provide talk therapy. Counsellors offer guidance on specific life issues. All can help — the best fit depends on your needs."
    },
    {
      question: "Is therapy covered by provincial health insurance?",
      answer: "Psychologists and psychiatrists may be partially covered. Most psychotherapy and counselling requires private insurance or out-of-pocket payment. Many employers offer Employee Assistance Programs (EAP) with free sessions."
    },
    {
      question: "How much does therapy cost?",
      answer: "Sessions typically range from $120-$250/hour depending on the provider and province. Many therapists offer sliding scale fees. Check if your insurance covers mental health services."
    },
    {
      question: "How do I claim my listing on DoINeedATherapist.org?",
      answer: "Click 'Claim Your Listing' on your listing page, enter your professional email, and verify ownership. Once claimed, you can edit your information, add photos, and upgrade for enhanced features."
    },
    {
      question: "What does it cost to be listed?",
      answer: "Claiming your listing is free forever. Reviews Plus ($9/mo) adds a Featured badge, your Google reviews, and top placement. Website ($49/mo) includes a full website on your own domain. See our pricing page for full details."
    },
  ],

  // Design personality
  design: {
    primaryColor: '#6B8F71',
    accentColor: '#3B82F6',
    personalityWord: 'calm',
    personalityIcon: 'MessageSquare',
    heroPattern: 'dots' as const,
    loadingMessages: [
      'Holding space...',
      'Taking a breath...',
      'Setting the tone...',
      'Creating a safe space...',
      'Listening carefully...',
    ],
    notFoundMessage: 'That page needs time to heal.',
    NT: "Northwest Territories",
    NU: "Nunavut",
    YT: "Yukon",
    AL: "Alabama",
    AK: "Alaska",
    AZ: "Arizona",
    AR: "Arkansas",
    CA: "California",
    CO: "Colorado",
    CT: "Connecticut",
    DE: "Delaware",
    FL: "Florida",
    GA: "Georgia",
    HI: "Hawaii",
    ID: "Idaho",
    IL: "Illinois",
    IN: "Indiana",
    IA: "Iowa",
    KS: "Kansas",
    KY: "Kentucky",
    LA: "Louisiana",
    ME: "Maine",
    MD: "Maryland",
    MA: "Massachusetts",
    MI: "Michigan",
    MN: "Minnesota",
    MS: "Mississippi",
    MO: "Missouri",
    MT: "Montana",
    NE: "Nebraska",
    NV: "Nevada",
    NH: "New Hampshire",
    NJ: "New Jersey",
    NM: "New Mexico",
    NY: "New York",
    NC: "North Carolina",
    ND: "North Dakota",
    OH: "Ohio",
    OK: "Oklahoma",
    OR: "Oregon",
    PA: "Pennsylvania",
    RI: "Rhode Island",
    SC: "South Carolina",
    SD: "South Dakota",
    TN: "Tennessee",
    TX: "Texas",
    UT: "Utah",
    VT: "Vermont",
    VA: "Virginia",
    WA: "Washington",
    WV: "West Virginia",
    WI: "Wisconsin",
    WY: "Wyoming",
    DC: "District of Columbia",
  },
};

export default verticalConfig;
